apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: ghcr.io/nest-analytics/demo-app:3532fd8d584aecb8806d8902ff8c372c93759502
          ports:
            - containerPort: 3000
  